// src/style/LoginPageStyles.js

// Perbarui path gambar latar belakang agar sesuai dengan lokasi baru file style ini
import loginBackground from '../assets/images/banana2.jpg'; // Naik satu level ke src/, lalu masuk ke assets/images/

export const loginPageStyles = {
  mainBox: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: `linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(${loginBackground})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: 'fixed',
    padding: { xs: 2, sm: 3, md: 4 },
  },
  commonContainer: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    py: { xs: 4, md: 0 },
  },
  leftBox: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: { xs: 'center', md: 'flex-start' },
    pr: { xs: 0, md: 6 },
    mb: { xs: 4, md: 0 },
    textAlign: { xs: 'center', md: 'left' },
    color: 'white',
    textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
    maxWidth: { xs: '100%', md: '500px' },
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    backdropFilter: 'blur(2px)',
    borderRadius: '16px',
    padding: { xs: 3, md: 4 },
    boxShadow: '0px 10px 30px rgba(0, 0, 0, 0.2)',
  },
  rightPaper: {
    padding: { xs: 4, sm: 5, md: 6 },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    borderRadius: '16px',
    width: { xs: '100%', sm: '80%', md: '360px' },
    maxWidth: '360px',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    boxShadow: '0px 10px 30px rgba(0, 0, 0, 0.3), 0 0 0 1px rgba(255, 255, 255, 0.4)',
  },
  rightPaperTitle: {
    mb: 4,
    fontWeight: 700,
    color: 'text.primary',
    textAlign: 'center',
    lineHeight: 1.3,
    textShadow: 'none',
    fontSize: '1.6rem',
  },
  linkTextSecondary: {
    color: 'text.secondary',
    fontWeight: 500,
  },
  linkPrimary: {
    color: 'primary.main',
    fontWeight: 700,
    cursor: 'pointer',
    '&:hover': { textDecoration: 'underline' },
  },
  watermark: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    textAlign: 'right',
    opacity: 0.9,
    textShadow: '1px 1px 2px rgba(0,0,0,0.7)',
    zIndex: 10,
    fontWeight: 500,
    color: 'white',
  },
};